### PR TITLE
Added logger name param support

### PR DESCRIPTION
**Pull request by nicoeft**

### CODE REVIEW

**Comment by james-e-morris** [comment]
@nicoeft thank you for your contribution. It looks like you've just added an override to the `filename` input that does the same thing as `filename`, and it is not propogated to `self.filename`. Can you provide an example where your use-case needs this `name` parameter on top of `filename`? Have you tried using `filename` to set the logger name? I believe if you pass a value into `filename` without a file extension, you will have the same result as your `name`.


Please also be careful about reformatting with a pull request. This adds extra confusion when performing a merge when the changes are not function, just your stylistic methods.

**Comment by nicoeft** [comment]
First of all thank you for the repository, very useful and I'm very sorry for the formatting changes, my bad.

Regarding the feature, I think it's useful to propagate the name functionality from logging logger so it allows a single file to have multiple issuers or origins, instead of having to define multiple log files . 

For example if you want to track what service or class generated the log, without the name feature you'll end up with multiple files like:

- logs/log_A.csv
- logs/log_B.csv
- logs/log_C.csv

 And although it might be useful in some cases, having a "name" column allows to merge all those logs in a single a file `logs/log.csv`, same as we already do with levelName (instead of having` logs/log_INFO.csv`,` logs/log_ERROR.csv` , etc.)

**Comment by james-e-morris** [comment]
I see... Well part of the issue here is going to be the file I/O stepping on each other. Even if you use two loggers with different names but the same filenames, you're going to have them stepping on each other as the loggers queue up the logs but have to wait for the other logger to finish before writing.

I tested out your suggestion and see intermittent file issues. For some reason it works okay at the start, but when I start logging a value of '4', it starts getting hung up. See below code and the output. 

Maybe I propose another solution: initialize your CSV logger at the main level, pass the reference down to your child processes (A,B,C, etc), and I include an optional `tag` when logging? This would basically be an extra input that is written to file (if you use `fmt`) similarly to the INFO, DEBUG, etc outputs.

example code:
```python
#!/usr/bin/python3

from src.csv_logger import CsvLogger
import logging
from time import sleep

filename = 'logs/log.csv'
level = logging.INFO
fmt = '%(asctime)s,%(name)s,%(message)s'
datefmt = '%Y/%m/%d %H:%M:%S'
max_size = 1024  # 1 kilobyte
max_files = 4  # 4 rotating files
header = ['date', 'value_1', 'value_2']

# Creat logger with csv rotating handler
csvlogger = CsvLogger(filename=filename,
                      name='logger1',
                      level=level,
                      fmt=fmt,
                      datefmt=datefmt,
                      max_size=max_size,
                      max_files=max_files,
                      header=header)
csvlogger2 = CsvLogger(filename=filename,
                       name='logger2',
                       level=level,
                       fmt=fmt,
                       datefmt=datefmt,
                       max_size=max_size,
                       max_files=max_files,
                       header=header)

# Log some records
for i in range(10):
    csvlogger.info([i, i * 2])
    csvlogger2.info('1')
    sleep(0.1)

# You can log list or string
csvlogger.info([1000.1, 2000.2])
csvlogger2.info('2')
csvlogger.critical('3000,4000')
csvlogger2.critical('3')

# Log some more records to trigger rollover
for i in range(50):
    csvlogger.info([i * 2, float(i**2)])
    csvlogger2.info('4')
    sleep(0.1)

# Read and print all of the logs from file after logging
all_logs = csvlogger.get_logs(evaluate=True)
for log in all_logs:
    print(log)
```

```python
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger1', 0, 0]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger1', 1, 2]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger1', 2, 4]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger1', 3, 6]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger1', 4, 8]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger1', 5, 10]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger1', 6, 12]
[datetime.datetime(2022, 1, 29, 18, 24, 56), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 7, 14]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 8, 16]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 9, 18]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 1]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 1000.1, 2000.2]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 2]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 3000, 4000]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 3]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 0, 0.0]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 2, 1.0]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 4, 4.0]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 6, 9.0]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 8, 16.0]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 10, 25.0]
[datetime.datetime(2022, 1, 29, 18, 24, 57), 'logger1', 12, 36.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 14, 49.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 16, 64.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 18, 81.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 20, 100.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 22, 121.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 24, 144.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 26, 169.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 28, 196.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 30, 225.0]
[datetime.datetime(2022, 1, 29, 18, 24, 58), 'logger1', 32, 256.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 34, 289.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 36, 324.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 38, 361.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 40, 400.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 42, 441.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 44, 484.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 46, 529.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 48, 576.0]
[datetime.datetime(2022, 1, 29, 18, 24, 59), 'logger1', 50, 625.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 52, 676.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 54, 729.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 56, 784.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 58, 841.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 60, 900.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 62, 961.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 64, 1024.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 66, 1089.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 68, 1156.0]
[datetime.datetime(2022, 1, 29, 18, 25), 'logger1', 70, 1225.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 72, 1296.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 74, 1369.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 76, 1444.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 78, 1521.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 80, 1600.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 82, 1681.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 84, 1764.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 86, 1849.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 88, 1936.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger1', 90, 2025.0]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger1', 92, 2116.0]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger1', 94, 2209.0]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger1', 96, 2304.0]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger1', 98, 2401.0]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 1), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger2', 4]
[datetime.datetime(2022, 1, 29, 18, 25, 2), 'logger2', 4]
```

**Comment by nicoeft** [comment]
True, that can be a real headache for use cases where logs can happen simultaneously and even more if exact logging order is crucial. I agree that the the `tag`  approach is way better. Thanks!  have a nice weekend

**Comment by james-e-morris** [comment]
@nicoeft I'm not finding an easy way to add the tag functionality as it would require editing deeper function in the inherited logger functionality. An alternative that may fit your needs is the ability to include caller information with your logger output. I didn't include all of the `format` options in my documentation, but there are more than just `asctime`, `message`, `levelname`. A setting that might help you would be `funcName`, so you can see what function called your logger. A trick with that is you could also package your logger into different functions just for the sake of including that function name. See below documentation and example with `funcName`.

/usr/lib/python3.8/logging/__init__.py:
```python
""
%(name)s            Name of the logger (logging channel)
    %(levelno)s         Numeric logging level for the message (DEBUG, INFO,
                        WARNING, ERROR, CRITICAL)
    %(levelname)s       Text logging level for the message ("DEBUG", "INFO",
                        "WARNING", "ERROR", "CRITICAL")
    %(pathname)s        Full pathname of the source file where the logging
                        call was issued (if available)
    %(filename)s        Filename portion of pathname
    %(module)s          Module (name portion of filename)
    %(lineno)d          Source line number where the logging call was issued
                        (if available)
    %(funcName)s        Function name
    %(created)f         Time when the LogRecord was created (time.time()
                        return value)
    %(asctime)s         Textual time when the LogRecord was created
    %(msecs)d           Millisecond portion of the creation time
    %(relativeCreated)d Time in milliseconds when the LogRecord was created,
                        relative to the time the logging module was loaded
                        (typically at application startup time)
    %(thread)d          Thread ID (if available)
    %(threadName)s      Thread name (if available)
    %(process)d         Process ID (if available)
    %(message)s         The result of record.getMessage(), computed just as
                        the record is emitted
"""
```

example.py:
```python
#!/usr/bin/python3

from src.csv_logger import CsvLogger
import logging
from time import sleep

filename = 'logs/log.csv'
level = logging.INFO
fmt = '%(asctime)s,%(funcName)s,%(message)s'
datefmt = '%Y/%m/%d %H:%M:%S'
max_size = 1024  # 1 kilobyte
max_files = 4  # 4 rotating files
header = ['date', 'value_1', 'value_2']

# Creat logger with csv rotating handler
csvlogger = CsvLogger(filename=filename,
                      level=level,
                      fmt=fmt,
                      datefmt=datefmt,
                      max_size=max_size,
                      max_files=max_files,
                      header=header)


def log_set_one():
    # Log some records
    for i in range(10):
        csvlogger.info([i, i * 2])
        sleep(0.1)


def log_set_two():
    # You can log list or string
    csvlogger.info([1000.1, 2000.2])
    csvlogger.critical('3000,4000')


def log_set_three():
    # Log some more records to trigger rollover
    for i in range(50):
        csvlogger.info([i * 2, float(i**2)])
        sleep(0.1)


log_set_one()
log_set_two()
log_set_three()
# Read and print all of the logs from file after logging
all_logs = csvlogger.get_logs(evaluate=True)
for log in all_logs:
    print(log)
```

output:
```
[datetime.datetime(2022, 1, 31, 14, 38, 57), '<module>', 4, 4.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 6, 9.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 8, 16.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 10, 25.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 12, 36.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 14, 49.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 16, 64.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 18, 81.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 20, 100.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 22, 121.0]
[datetime.datetime(2022, 1, 31, 14, 38, 58), '<module>', 24, 144.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 26, 169.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 28, 196.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 30, 225.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 32, 256.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 34, 289.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 36, 324.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 38, 361.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 40, 400.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 42, 441.0]
[datetime.datetime(2022, 1, 31, 14, 38, 59), '<module>', 44, 484.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 46, 529.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 48, 576.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 50, 625.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 52, 676.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 54, 729.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 56, 784.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 58, 841.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 60, 900.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 62, 961.0]
[datetime.datetime(2022, 1, 31, 14, 39), '<module>', 64, 1024.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 66, 1089.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 68, 1156.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 70, 1225.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 72, 1296.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 74, 1369.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 76, 1444.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 78, 1521.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 80, 1600.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 82, 1681.0]
[datetime.datetime(2022, 1, 31, 14, 39, 1), '<module>', 84, 1764.0]
[datetime.datetime(2022, 1, 31, 14, 39, 2), '<module>', 86, 1849.0]
[datetime.datetime(2022, 1, 31, 14, 39, 2), '<module>', 88, 1936.0]
[datetime.datetime(2022, 1, 31, 14, 39, 2), '<module>', 90, 2025.0]
[datetime.datetime(2022, 1, 31, 14, 39, 2), '<module>', 92, 2116.0]
[datetime.datetime(2022, 1, 31, 14, 39, 2), '<module>', 94, 2209.0]
[datetime.datetime(2022, 1, 31, 14, 39, 2), '<module>', 96, 2304.0]
[datetime.datetime(2022, 1, 31, 14, 39, 2), '<module>', 98, 2401.0]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 0, 0]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 1, 2]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 2, 4]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 3, 6]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 4, 8]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 5, 10]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 6, 12]
[datetime.datetime(2022, 1, 31, 14, 40, 57), 'log_set_one', 7, 14]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_one', 8, 16]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_one', 9, 18]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_two', 1000.1, 2000.2]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_two', 3000, 4000]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 0, 0.0]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 2, 1.0]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 4, 4.0]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 6, 9.0]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 8, 16.0]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 10, 25.0]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 12, 36.0]
[datetime.datetime(2022, 1, 31, 14, 40, 58), 'log_set_three', 14, 49.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 16, 64.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 18, 81.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 20, 100.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 22, 121.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 24, 144.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 26, 169.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 28, 196.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 30, 225.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 32, 256.0]
[datetime.datetime(2022, 1, 31, 14, 40, 59), 'log_set_three', 34, 289.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 36, 324.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 38, 361.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 40, 400.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 42, 441.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 44, 484.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 46, 529.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 48, 576.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 50, 625.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 52, 676.0]
[datetime.datetime(2022, 1, 31, 14, 41), 'log_set_three', 54, 729.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 56, 784.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 58, 841.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 60, 900.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 62, 961.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 64, 1024.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 66, 1089.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 68, 1156.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 70, 1225.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 72, 1296.0]
[datetime.datetime(2022, 1, 31, 14, 41, 1), 'log_set_three', 74, 1369.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 76, 1444.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 78, 1521.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 80, 1600.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 82, 1681.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 84, 1764.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 86, 1849.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 88, 1936.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 90, 2025.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 92, 2116.0]
[datetime.datetime(2022, 1, 31, 14, 41, 2), 'log_set_three', 94, 2209.0]
[datetime.datetime(2022, 1, 31, 14, 41, 3), 'log_set_three', 96, 2304.0]
[datetime.datetime(2022, 1, 31, 14, 41, 3), 'log_set_three', 98, 2401.0]
```

**Comment by james-e-morris** [comment]
@nicoeft scratch that.... I think I have a solution for you..

**Comment by james-e-morris** [comment]
@nicoeft please take a look at the latest release:
https://github.com/Morrious/csv-logger/releases/tag/1.2.2

It has also been published to pip

**Pull request closed without merging**
